const NUM_HORIZONTAL_LINES = 11; // Keep above 0
const GRID_SPACING = 75;
const GRID_HEIGHT = GRID_SPACING * NUM_HORIZONTAL_LINES;

const NUM_VERTICAL_LINES = 16; // Keep above 0
const GRID_WIDTH = GRID_SPACING * NUM_VERTICAL_LINES;

const IMAGE_SCALE = 3;


export { NUM_HORIZONTAL_LINES, GRID_SPACING, GRID_HEIGHT, NUM_VERTICAL_LINES, GRID_WIDTH, IMAGE_SCALE };